  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Notes / Blog"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"
