title = "Almost surely"
author = "Martin Trapp"
#copyright = "2020-2021"
description = """<b>Martin Trapp</b>
AoF Postdoctoral Researcher
Aalto University, Finland"""
profilePicture = "images/picture2.jpg"
keywords = ""
favicon = ""
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
#use = "katex"  # options: "katex", "mathjax". default is "katex".
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/trappmartin"

# [[socialIcons]]
# icon = "fab fa-twitter"
# title = "Twitter"
# url = "https://twitter.com/martin_trapp"

[[socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://ellis.social/@trappmartin"

[[socialIcons]]
icon = "fas fa-graduation-cap"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=GwCrZP4AAAAJ"

[[socialIcons]]
icon = "fab fa-orcid"
title = "ORCiD"
url = "https://orcid.org/0000-0003-1725-3381"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:martin.trapp@aalto.fi"

[mermaid]
# enable = true
